### ISSUE TITLE
Release optional version without activity for those of us that can actually read

### ISSUE THREAD

**Issue by JacobDB** [zacharee/NachoNotch#1]
Thank you for making this app, it's definitely going to come in handy now that basically all major Android phones are getting notches.

I saw in a recent update that you added an activity for the dummies that can't be bothered to read the instructions in the Play store; would you consider release an alternate APK without the activity, if only on GitHub for side-loading? I'd prefer not to have to have the additional icon in my apps list if possible, and I don't really want to switch to a different launcher so that I can hide it.

I get it if it's too much hassle, but I figured it was worth asking. 🙂

**Comment by zacharee** [comment]
Check out version 4

**Comment by JacobDB** [comment]
You don't have any tags set up; would that be this version? https://github.com/zacharee/NachoNotch/blob/0400accc401044a084f018c74bce59dbb00db8cb/app/release/app-release.apk

**Comment by zacharee** [comment]
No. Update from the Play Store and open the app.


On 5 abr. 2018 at 9:31 AM, <Jacob Bearce <notifications@github.com>> wrote:

You don't have any tags set up; would that be this version?
https://github.com/zacharee/NachoNotch/blob/0400accc401044a084f018c74bce59dbb00db8cb/app/release/app-release.apk

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/zacharee/NachoNotch/issues/1#issuecomment-378936606>,
or mute the thread
